'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace csfacturacion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="csticketServiceBinding", [Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class csticketService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private UploadarchivoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrarTicketOperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrarTicket33OperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrarTicketGlobal33OperationCompleted As System.Threading.SendOrPostCallback
        
        Private validarTicketOperationCompleted As System.Threading.SendOrPostCallback
        
        Private validarTicket33OperationCompleted As System.Threading.SendOrPostCallback
        
        Private obtenerDatosticketOperationCompleted As System.Threading.SendOrPostCallback
        
        Private obtenerDatosticket33OperationCompleted As System.Threading.SendOrPostCallback
        
        Private uploadzipOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CointechToCsPlug.My.MySettings.Default.CointechToCsPlug_csfacturacion_csticketService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event UploadarchivoCompleted As UploadarchivoCompletedEventHandler
        
        '''<remarks/>
        Public Event timbrarTicketCompleted As timbrarTicketCompletedEventHandler
        
        '''<remarks/>
        Public Event timbrarTicket33Completed As timbrarTicket33CompletedEventHandler
        
        '''<remarks/>
        Public Event timbrarTicketGlobal33Completed As timbrarTicketGlobal33CompletedEventHandler
        
        '''<remarks/>
        Public Event validarTicketCompleted As validarTicketCompletedEventHandler
        
        '''<remarks/>
        Public Event validarTicket33Completed As validarTicket33CompletedEventHandler
        
        '''<remarks/>
        Public Event obtenerDatosticketCompleted As obtenerDatosticketCompletedEventHandler
        
        '''<remarks/>
        Public Event obtenerDatosticket33Completed As obtenerDatosticket33CompletedEventHandler
        
        '''<remarks/>
        Public Event uploadzipCompleted As uploadzipCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#Uploadarchivo", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function Uploadarchivo(ByVal Password As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As <System.Xml.Serialization.SoapElementAttribute("respuestaUpload")> respuestaUpload
            Dim results() As Object = Me.Invoke("Uploadarchivo", New Object() {Password, Archivo})
            Return CType(results(0),respuestaUpload)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UploadarchivoAsync(ByVal Password As String, ByVal Archivo() As Byte)
            Me.UploadarchivoAsync(Password, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UploadarchivoAsync(ByVal Password As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.UploadarchivoOperationCompleted Is Nothing) Then
                Me.UploadarchivoOperationCompleted = AddressOf Me.OnUploadarchivoOperationCompleted
            End If
            Me.InvokeAsync("Uploadarchivo", New Object() {Password, Archivo}, Me.UploadarchivoOperationCompleted, userState)
        End Sub
        
        Private Sub OnUploadarchivoOperationCompleted(ByVal arg As Object)
            If (Not (Me.UploadarchivoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UploadarchivoCompleted(Me, New UploadarchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#timbrarTicket", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function timbrarTicket(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaTimbrado")> respuestaTimbrado
            Dim results() As Object = Me.Invoke("timbrarTicket", New Object() {cRefid, Password, cDatosreceptor})
            Return CType(results(0),respuestaTimbrado)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarTicketAsync(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String)
            Me.timbrarTicketAsync(cRefid, Password, cDatosreceptor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarTicketAsync(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String, ByVal userState As Object)
            If (Me.timbrarTicketOperationCompleted Is Nothing) Then
                Me.timbrarTicketOperationCompleted = AddressOf Me.OntimbrarTicketOperationCompleted
            End If
            Me.InvokeAsync("timbrarTicket", New Object() {cRefid, Password, cDatosreceptor}, Me.timbrarTicketOperationCompleted, userState)
        End Sub
        
        Private Sub OntimbrarTicketOperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarTicketCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarTicketCompleted(Me, New timbrarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#timbrarTicket33", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function timbrarTicket33(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String, ByVal cRfcEmisor As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaTimbrado33")> respuestaTimbrado33
            Dim results() As Object = Me.Invoke("timbrarTicket33", New Object() {cRefid, Password, cDatosreceptor, cRfcEmisor})
            Return CType(results(0),respuestaTimbrado33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarTicket33Async(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String, ByVal cRfcEmisor As String)
            Me.timbrarTicket33Async(cRefid, Password, cDatosreceptor, cRfcEmisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarTicket33Async(ByVal cRefid As String, ByVal Password As String, ByVal cDatosreceptor As String, ByVal cRfcEmisor As String, ByVal userState As Object)
            If (Me.timbrarTicket33OperationCompleted Is Nothing) Then
                Me.timbrarTicket33OperationCompleted = AddressOf Me.OntimbrarTicket33OperationCompleted
            End If
            Me.InvokeAsync("timbrarTicket33", New Object() {cRefid, Password, cDatosreceptor, cRfcEmisor}, Me.timbrarTicket33OperationCompleted, userState)
        End Sub
        
        Private Sub OntimbrarTicket33OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarTicket33CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarTicket33Completed(Me, New timbrarTicket33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#timbrarTicketGlobal33", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function timbrarTicketGlobal33(ByVal Password As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte) As <System.Xml.Serialization.SoapElementAttribute("respuestaTimbradoGlobal33")> respuestaTimbradoGlobal33
            Dim results() As Object = Me.Invoke("timbrarTicketGlobal33", New Object() {Password, Archivo})
            Return CType(results(0),respuestaTimbradoGlobal33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarTicketGlobal33Async(ByVal Password As String, ByVal Archivo() As Byte)
            Me.timbrarTicketGlobal33Async(Password, Archivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarTicketGlobal33Async(ByVal Password As String, ByVal Archivo() As Byte, ByVal userState As Object)
            If (Me.timbrarTicketGlobal33OperationCompleted Is Nothing) Then
                Me.timbrarTicketGlobal33OperationCompleted = AddressOf Me.OntimbrarTicketGlobal33OperationCompleted
            End If
            Me.InvokeAsync("timbrarTicketGlobal33", New Object() {Password, Archivo}, Me.timbrarTicketGlobal33OperationCompleted, userState)
        End Sub
        
        Private Sub OntimbrarTicketGlobal33OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarTicketGlobal33CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarTicketGlobal33Completed(Me, New timbrarTicketGlobal33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#validarTicket", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function validarTicket(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcemisor As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaValidarticket")> respuestaValidarticket
            Dim results() As Object = Me.Invoke("validarTicket", New Object() {dTotal, cRefid, cRfcemisor})
            Return CType(results(0),respuestaValidarticket)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validarTicketAsync(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcemisor As String)
            Me.validarTicketAsync(dTotal, cRefid, cRfcemisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validarTicketAsync(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcemisor As String, ByVal userState As Object)
            If (Me.validarTicketOperationCompleted Is Nothing) Then
                Me.validarTicketOperationCompleted = AddressOf Me.OnvalidarTicketOperationCompleted
            End If
            Me.InvokeAsync("validarTicket", New Object() {dTotal, cRefid, cRfcemisor}, Me.validarTicketOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidarTicketOperationCompleted(ByVal arg As Object)
            If (Not (Me.validarTicketCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validarTicketCompleted(Me, New validarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#validarTicket33", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function validarTicket33(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcReceptor As String, ByVal cRfcemisor As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaValidarticket33")> respuestaValidarticket33
            Dim results() As Object = Me.Invoke("validarTicket33", New Object() {dTotal, cRefid, cRfcReceptor, cRfcemisor})
            Return CType(results(0),respuestaValidarticket33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validarTicket33Async(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcReceptor As String, ByVal cRfcemisor As String)
            Me.validarTicket33Async(dTotal, cRefid, cRfcReceptor, cRfcemisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validarTicket33Async(ByVal dTotal As Double, ByVal cRefid As String, ByVal cRfcReceptor As String, ByVal cRfcemisor As String, ByVal userState As Object)
            If (Me.validarTicket33OperationCompleted Is Nothing) Then
                Me.validarTicket33OperationCompleted = AddressOf Me.OnvalidarTicket33OperationCompleted
            End If
            Me.InvokeAsync("validarTicket33", New Object() {dTotal, cRefid, cRfcReceptor, cRfcemisor}, Me.validarTicket33OperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidarTicket33OperationCompleted(ByVal arg As Object)
            If (Not (Me.validarTicket33CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validarTicket33Completed(Me, New validarTicket33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#obtenerDatosticket", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function obtenerDatosticket(ByVal cRefid As String, ByVal Password As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaObtenerdatosticket")> respuestaObtenerdatosticket
            Dim results() As Object = Me.Invoke("obtenerDatosticket", New Object() {cRefid, Password})
            Return CType(results(0),respuestaObtenerdatosticket)
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerDatosticketAsync(ByVal cRefid As String, ByVal Password As String)
            Me.obtenerDatosticketAsync(cRefid, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerDatosticketAsync(ByVal cRefid As String, ByVal Password As String, ByVal userState As Object)
            If (Me.obtenerDatosticketOperationCompleted Is Nothing) Then
                Me.obtenerDatosticketOperationCompleted = AddressOf Me.OnobtenerDatosticketOperationCompleted
            End If
            Me.InvokeAsync("obtenerDatosticket", New Object() {cRefid, Password}, Me.obtenerDatosticketOperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerDatosticketOperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerDatosticketCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerDatosticketCompleted(Me, New obtenerDatosticketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#obtenerDatosticket33", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function obtenerDatosticket33(ByVal cRefid As String, ByVal Password As String, ByVal cRfcEmisor As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaObtenerdatosticket33")> respuestaObtenerdatosticket33
            Dim results() As Object = Me.Invoke("obtenerDatosticket33", New Object() {cRefid, Password, cRfcEmisor})
            Return CType(results(0),respuestaObtenerdatosticket33)
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerDatosticket33Async(ByVal cRefid As String, ByVal Password As String, ByVal cRfcEmisor As String)
            Me.obtenerDatosticket33Async(cRefid, Password, cRfcEmisor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerDatosticket33Async(ByVal cRefid As String, ByVal Password As String, ByVal cRfcEmisor As String, ByVal userState As Object)
            If (Me.obtenerDatosticket33OperationCompleted Is Nothing) Then
                Me.obtenerDatosticket33OperationCompleted = AddressOf Me.OnobtenerDatosticket33OperationCompleted
            End If
            Me.InvokeAsync("obtenerDatosticket33", New Object() {cRefid, Password, cRfcEmisor}, Me.obtenerDatosticket33OperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerDatosticket33OperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerDatosticket33CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerDatosticket33Completed(Me, New obtenerDatosticket33CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:wsdlcsticket#Uploadzip", RequestNamespace:="urn:https://www.csfacturacion.com", ResponseNamespace:="urn:https://www.csfacturacion.com")>  _
        Public Function uploadzip(<System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> ByVal Archivo() As Byte, ByVal nombreArchivo As String) As <System.Xml.Serialization.SoapElementAttribute("respuestaUploadzip")> respuestaUploadzip
            Dim results() As Object = Me.Invoke("uploadzip", New Object() {Archivo, nombreArchivo})
            Return CType(results(0),respuestaUploadzip)
        End Function
        
        '''<remarks/>
        Public Overloads Sub uploadzipAsync(ByVal Archivo() As Byte, ByVal nombreArchivo As String)
            Me.uploadzipAsync(Archivo, nombreArchivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub uploadzipAsync(ByVal Archivo() As Byte, ByVal nombreArchivo As String, ByVal userState As Object)
            If (Me.uploadzipOperationCompleted Is Nothing) Then
                Me.uploadzipOperationCompleted = AddressOf Me.OnuploadzipOperationCompleted
            End If
            Me.InvokeAsync("uploadzip", New Object() {Archivo, nombreArchivo}, Me.uploadzipOperationCompleted, userState)
        End Sub
        
        Private Sub OnuploadzipOperationCompleted(ByVal arg As Object)
            If (Not (Me.uploadzipCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent uploadzipCompleted(Me, New uploadzipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaUpload
        
        Private msjField As String
        
        Private resultadoField As Boolean
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaUploadzip
        
        Private mensajeField As String
        
        Private resumenField As String
        
        Private erroresField As String
        
        Private resultadoField As Boolean
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resumen() As String
            Get
                Return Me.resumenField
            End Get
            Set
                Me.resumenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Errores() As String
            Get
                Return Me.erroresField
            End Get
            Set
                Me.erroresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaObtenerdatosticket33
        
        Private msjField As String
        
        Private resultadoField As Boolean
        
        Private cDatosticketField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cDatosticket() As String
            Get
                Return Me.cDatosticketField
            End Get
            Set
                Me.cDatosticketField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaObtenerdatosticket
        
        Private msjField As String
        
        Private resultadoField As Boolean
        
        Private cDatosticketField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cDatosticket() As String
            Get
                Return Me.cDatosticketField
            End Get
            Set
                Me.cDatosticketField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaValidarticket33
        
        Private msjField As String
        
        Private resultadoField As Boolean
        
        Private cDatosreceptorField As String
        
        Private xML64Field As String
        
        Private pDF64Field As String
        
        Private nAMEFILEField As String
        
        Private iEPSField As Boolean
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cDatosreceptor() As String
            Get
                Return Me.cDatosreceptorField
            End Get
            Set
                Me.cDatosreceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML64() As String
            Get
                Return Me.xML64Field
            End Get
            Set
                Me.xML64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF64() As String
            Get
                Return Me.pDF64Field
            End Get
            Set
                Me.pDF64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAMEFILE() As String
            Get
                Return Me.nAMEFILEField
            End Get
            Set
                Me.nAMEFILEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IEPS() As Boolean
            Get
                Return Me.iEPSField
            End Get
            Set
                Me.iEPSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaValidarticket
        
        Private msjField As String
        
        Private resultadoField As Boolean
        
        Private cDatosreceptorField As String
        
        Private xML64Field As String
        
        Private pDF64Field As String
        
        Private nAMEFILEField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cDatosreceptor() As String
            Get
                Return Me.cDatosreceptorField
            End Get
            Set
                Me.cDatosreceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML64() As String
            Get
                Return Me.xML64Field
            End Get
            Set
                Me.xML64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF64() As String
            Get
                Return Me.pDF64Field
            End Get
            Set
                Me.pDF64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAMEFILE() As String
            Get
                Return Me.nAMEFILEField
            End Get
            Set
                Me.nAMEFILEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaTimbradoGlobal33
        
        Private msjField As String
        
        Private xML64Field As String
        
        Private pDF64Field As String
        
        Private pDFField() As Byte
        
        Private xMLField() As Byte
        
        Private nAMEFILEField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML64() As String
            Get
                Return Me.xML64Field
            End Get
            Set
                Me.xML64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF64() As String
            Get
                Return Me.pDF64Field
            End Get
            Set
                Me.pDF64Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property XML() As Byte()
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAMEFILE() As String
            Get
                Return Me.nAMEFILEField
            End Get
            Set
                Me.nAMEFILEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaTimbrado33
        
        Private msjField As String
        
        Private xML64Field As String
        
        Private pDF64Field As String
        
        Private pDFField() As Byte
        
        Private xMLField() As Byte
        
        Private nAMEFILEField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML64() As String
            Get
                Return Me.xML64Field
            End Get
            Set
                Me.xML64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF64() As String
            Get
                Return Me.pDF64Field
            End Get
            Set
                Me.pDF64Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property XML() As Byte()
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAMEFILE() As String
            Get
                Return Me.nAMEFILEField
            End Get
            Set
                Me.nAMEFILEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="https://www.csfacturacion.com")>  _
    Partial Public Class respuestaTimbrado
        
        Private msjField As String
        
        Private xML64Field As String
        
        Private pDF64Field As String
        
        Private pDFField() As Byte
        
        Private xMLField() As Byte
        
        Private nAMEFILEField As String
        
        '''<remarks/>
        Public Property Msj() As String
            Get
                Return Me.msjField
            End Get
            Set
                Me.msjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XML64() As String
            Get
                Return Me.xML64Field
            End Get
            Set
                Me.xML64Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PDF64() As String
            Get
                Return Me.pDF64Field
            End Get
            Set
                Me.pDF64Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")>  _
        Public Property XML() As Byte()
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAMEFILE() As String
            Get
                Return Me.nAMEFILEField
            End Get
            Set
                Me.nAMEFILEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub UploadarchivoCompletedEventHandler(ByVal sender As Object, ByVal e As UploadarchivoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UploadarchivoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaUpload
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaUpload)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub timbrarTicketCompletedEventHandler(ByVal sender As Object, ByVal e As timbrarTicketCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarTicketCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaTimbrado
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaTimbrado)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub timbrarTicket33CompletedEventHandler(ByVal sender As Object, ByVal e As timbrarTicket33CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarTicket33CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaTimbrado33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaTimbrado33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub timbrarTicketGlobal33CompletedEventHandler(ByVal sender As Object, ByVal e As timbrarTicketGlobal33CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarTicketGlobal33CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaTimbradoGlobal33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaTimbradoGlobal33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub validarTicketCompletedEventHandler(ByVal sender As Object, ByVal e As validarTicketCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validarTicketCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaValidarticket
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaValidarticket)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub validarTicket33CompletedEventHandler(ByVal sender As Object, ByVal e As validarTicket33CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validarTicket33CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaValidarticket33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaValidarticket33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub obtenerDatosticketCompletedEventHandler(ByVal sender As Object, ByVal e As obtenerDatosticketCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerDatosticketCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaObtenerdatosticket
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaObtenerdatosticket)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub obtenerDatosticket33CompletedEventHandler(ByVal sender As Object, ByVal e As obtenerDatosticket33CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerDatosticket33CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaObtenerdatosticket33
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaObtenerdatosticket33)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub uploadzipCompletedEventHandler(ByVal sender As Object, ByVal e As uploadzipCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class uploadzipCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As respuestaUploadzip
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),respuestaUploadzip)
            End Get
        End Property
    End Class
End Namespace
